;-----------------------------------------------------------------------------------------------------------------;
; The framework's account configuration file with settings for a single trade account.                            ;
;-----------------------------------------------------------------------------------------------------------------;
; All three configuration files (user, terminal, account) are combined into a single configuration. The terminal  ;
; configuration takes precedence over the user configuration, and the account configuration takes precedence over ;
; the terminal configuration.                                                                                     ;
;-----------------------------------------------------------------------------------------------------------------;
; The file format supports full-line and inline comments. This differs from the standard Windows .ini file format ;
; which doesn't support inline comments.                                                                          ;
;                                                                                                                 ;
; Everything after a semicolon ";" is interpreted as comment. To use a semicolon ";" as part of the config value  ;
; the full value must be wrapped in double quotes.                                                                ;
;                                                                                                                 ;
; Boolean values can be specified as one of:                                                                      ;
;     1 | 0                                                                                                       ;
;    on | off                                                                                                     ;
;   yes | no                                                                                                      ;
;  true | false                                                                                                   ;
;                                                                                                                 ;
; File paths support both forward and backward slashes.                                                           ;
;-----------------------------------------------------------------------------------------------------------------;
; Example:
[SectionName]
; a full-line comment
Key1 = value                        ; a config value followed by an inline comment
Key2 = "string with ; semicolon"    ; a config value containing a literal semicolon


[Account]                           ; settings in this section are read only from the account configuration file
Company        = <company-name>
Currency       = <currency>
Name           = <account-holder>
Alias          = <alias>            ; any string, obfuscates the account number in outbound messages (e.g. "live-account-USD")
MaxOpenTickets = <integer>          ; maximum number of open tickets
MaxOpenLots    = <integer>          ; maximum lot size of open positions
Type           = demo|real          ; real account type (some brokers set up demo accounts to look just like live accounts)
