;
; There must be no whitespace before and after the equal sign.
; @see  https://www.metatrader4.com/en/trading-platform/help/service/start_conf_file
;

; General settings
EnableDDE=false
EnableNews=false

; Proxy settings (hel01)
ProxyEnable=true
ProxyServer=127.0.0.1:50088
ProxyType=SOCKS5

; FTP settings
FTPEnable=false

; MQL runtime settings
ExpertsEnable=true
ExpertsDllImport=true
ExpertsDllConfirm=false
ExpertsExpImport=true
ExpertsTrades=true
ExpertsTradesConfirm=false

; MQL launch settings
;Symbol=EURUSD
;Period=M15
;Template=Empty.tpl
;Expert=MyCustomEA
;ExpertParameters=
Script=LoadMT4Expander
ScriptParameters=
